### ISSUE TITLE
Improve the parsing of results files to cope with multiple header rows in the results

### ISSUE THREAD

**Issue by julianharty** [commercetest/pepperbox-analysis#1]
Some tests involve restarting the consumer, the consumer writes a new header row each time. The existing scripts don't cope with these. Let's help them do so.

**Comment by ISNIT0** [comment]
👍

**Comment by ISNIT0** [comment]
Fixed in e4b1faae14564194b06762f01003f58b71807ada Would be nice to get rid of the for loop

**Comment by julianharty** [comment]
The next file to tackle is `extractResults.sh`

**Comment by ISNIT0** [comment]
No longer necessary
