### ISSUE TITLE
Generate mini-csv files suitable to import directly and graph

### ISSUE THREAD

**Issue by julianharty** [commercetest/pepperbox-analysis#3]
Currently we generate a composite output in json. We have been manually copy pasting data from it to put in spreadsheets. This is becoming cumbersome so it's time to make the data easier to process and import.

**Comment by ISNIT0** [comment]
We've now got pluck scripts as an intermediate solution, need to streamline the entire process though

**Comment by ISNIT0** [comment]
This is now done
